In [1]:
import pandas as pd

In [7]:
data = {
    'expense_name' : ['sushi', 'biryani', 'rent'],
    'price' : [1000, 500, 50000] 
}

In [8]:
df = pd.DataFrame(data=data)

In [9]:
df.to_csv('expenses.csv', index=False)

In [6]:
df.head()

      name category  expense
0    sushi     food     1000
1  biryani     food      500
2     rent     home    50000

In [21]:
new_row = pd.DataFrame({'name' : ['trip'], 'category' : ['home'], 'expense' : ['100000']})

In [22]:
pd.concat([df, new_row], axis=0)

      name category expense
0    sushi     food    1000
1  biryani     food     500
2     rent     home   50000
0     trip     home  100000

In [10]:
df = pd.read_csv('expenses.csv')

In [11]:
df.head()

  expense_name  price
0        sushi   1000
1      biryani    500
2         rent  50000
3      clothes   5000